project_id = "fyfqyeouyxotohtxlbdg"

[functions.enhance-prompt]
verify_jwt = false

[functions.text-to-speech]
verify_jwt = false

[functions.heygen-video]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.did-avatar]
verify_jwt = false

[functions.transcribe-audio]
verify_jwt = false
